services:
  - type: web
    name: fashion-stop-ecommerce
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: fashion-stop-db
    databaseName: fashionstop
    plan: free
